version: "3.8"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    build:
      context: ./client/flash-typing
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
